# Generated by Django 4.1.2 on 2022-10-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, verbose_name='Location Name')),
                ('location_description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_tag', models.CharField(max_length=30)),
                ('cow_sex', models.CharField(max_length=30)),
                ('cow_vaccinations', models.CharField(max_length=30)),
                ('cow_notes', models.CharField(max_length=200)),
                ('cow_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.farmlocations')),
            ],
        ),
    ]
