# Generated by Django 4.1.2 on 2022-12-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='cow_PARENT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cow'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='cow_sex',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='female', max_length=6),
        ),
    ]
