# Generated by Django 4.1.2 on 2022-12-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cow_cow_parent_alter_cow_cow_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stripe_product_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cow',
            name='cow_PARENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.cow'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='cow_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cow',
            name='cow_vaccinations',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
