# Generated by Django 4.1.2 on 2022-12-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_price_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
            preserve_default=False,
        ),
    ]
